[agent]
# 绑定地址
bind = "0.0.0.0:9813"
# server/agent 认证 token
api_token = "TOKEN"
# 生成的 WireGuard / Bird 配置写入路径
wg_path = "/path/to/wg"
bird_path = "/path/to/bird"
# 协议版本
version = 1
# 是否开放对外peering
is_open = true
# 是否需要人工验证
is_verify = false
# 额外信息
extra_msg = "hello world"

[agent.net]
## 此节点公网环境
# 是否支持 IPv4
ipv4 = true
# 是否支持 IPv6
ipv6 = true
# 是否支持 NAT
accept_nat = true
# 是否允许中国大陆 Peering
cn = false

[agent.dn42]
## 此节点部署的 DN42 相关信息
asn = 4242423322
ipv4 = "DN42_IPv4_ADDRESS"
ipv6 = "DN42_IPv6_ADDRESS"
lla = "DN42_LLA_ADDRESS"
wgkey = "DN42_WG_KEY"